-- METIER
IF OBJECT_ID('dbo.METIER','U') IS NULL
CREATE TABLE dbo.METIER (
  id_metier INT IDENTITY(1,1) PRIMARY KEY,
  nom_metier NVARCHAR(150) NOT NULL UNIQUE
);

-- CORPS_METIER
IF OBJECT_ID('dbo.CORPS_METIER','U') IS NULL
CREATE TABLE dbo.CORPS_METIER (
  id_corps INT IDENTITY(1,1) PRIMARY KEY,
  nom_corps NVARCHAR(150) NOT NULL,
  id_metier INT NOT NULL FOREIGN KEY REFERENCES dbo.METIER(id_metier),
  CONSTRAINT UQ_CORPS UNIQUE(nom_corps, id_metier)
);

-- ACTIVITE
IF OBJECT_ID('dbo.ACTIVITE','U') IS NULL
CREATE TABLE dbo.ACTIVITE (
  id_activite INT IDENTITY(1,1) PRIMARY KEY,
  nom_activite NVARCHAR(150) NOT NULL,
  id_corps INT NOT NULL FOREIGN KEY REFERENCES dbo.CORPS_METIER(id_corps),
  CONSTRAINT UQ_ACTIVITE UNIQUE(nom_activite, id_corps)
);

-- PRODUIT
IF OBJECT_ID('dbo.PRODUIT','U') IS NULL
CREATE TABLE dbo.PRODUIT (
  id_produit INT IDENTITY(1,1) PRIMARY KEY,
  nom_produit NVARCHAR(200) NOT NULL,
  id_activite INT NOT NULL FOREIGN KEY REFERENCES dbo.ACTIVITE(id_activite),
  CONSTRAINT UQ_PRODUIT UNIQUE(nom_produit, id_activite)
);

-- VARIETE
IF OBJECT_ID('dbo.VARIETE','U') IS NULL
CREATE TABLE dbo.VARIETE (
  id_variete INT IDENTITY(1,1) PRIMARY KEY,
  nom_variete NVARCHAR(200) NOT NULL,
  id_produit INT NOT NULL FOREIGN KEY REFERENCES dbo.PRODUIT(id_produit),
  CONSTRAINT UQ_VARIETE UNIQUE(nom_variete, id_produit)
);
