-- Trace columns
IF COL_LENGTH('dbo.INDICE','load_ts') IS NULL
  ALTER TABLE dbo.INDICE ADD load_ts DATETIME2 NOT NULL CONSTRAINT DF_INDICE_load_ts DEFAULT SYSUTCDATETIME();
IF COL_LENGTH('dbo.PONDERATION','load_ts') IS NULL
  ALTER TABLE dbo.PONDERATION ADD load_ts DATETIME2 NOT NULL CONSTRAINT DF_POND_load_ts DEFAULT SYSUTCDATETIME();

-- Uniques (idempotence)
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='UQ_INDICE_KEYS' AND object_id=OBJECT_ID('dbo.INDICE'))
  ALTER TABLE dbo.INDICE ADD CONSTRAINT UQ_INDICE_KEYS UNIQUE (annee, id_reference, id_ville, type_indice);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='UQ_POND_KEYS' AND object_id=OBJECT_ID('dbo.PONDERATION'))
  ALTER TABLE dbo.PONDERATION ADD CONSTRAINT UQ_POND_KEYS UNIQUE (annee, id_reference, niveau, id_ville, id_region);
